apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: dev-kubernetes-external-secrets
  labels:
    helm.sh/chart: kubernetes-external-secrets-4.0.0
    $patch: delet
    app.kubernetes.io/managed-by: Helm
    $patch: delete
