apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-kubernetes-external-secrets
  namespace: "kubernetes-external-secrets"
  labels:
    helm.sh/chart: kubernetes-external-secrets-4.0.0
    $patch: delet
    app.kubernetes.io/managed-by: Helm
    $patch: delete
