apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: demo
spec:
  backendType: alicloudSecretsManager
  # optional: specify role to assume using provided access key ID and access key secret when retrieving the data
  roleArn: acs:ram::228462691213768868:role/demo
  dataFrom:
  - db_cred
# Version Stage in Alibaba Cloud KMS Secrets Manager. Optional, default value is ACSCurrent
  versionStage: ACSCurrent
